airbnb_rj:
  target: local
  outputs:
    local:
      type: postgres
      host: localhost
      user: peon
      password: Gotadelimao123
      port: 5432
      dbname: home
      schema: airbnb
      threads: 4
        