with source as (
      select * from {{ source('air_rj', 'bronze_listings') }}
),
renamed as (
    select
        {{ adapter.quote("id") }} as listing_id,
        {{ adapter.quote("listing_url") }},
        {{ adapter.quote("scrape_id") }} as listing_scrape_id,
        {{ adapter.quote("last_scraped") }} as listing_last_scraped,
        {{ adapter.quote("source") }} as listing_source,
        {{ adapter.quote("name") }} as listing_name,
        {{ adapter.quote("description") }} as listing_description,
        {{ adapter.quote("neighborhood_overview") }},
        {{ adapter.quote("picture_url") }} as listing_picture_url,
        {{ adapter.quote("host_id") }} as listing_host_id,
        {{ adapter.quote("host_url") }} as listing_host_url,
        {{ adapter.quote("host_name") }} as listing_host_name,
        {{ adapter.quote("host_since") }} as listing_host_since,
        {{ adapter.quote("host_location") }} as listing_host_location,
        {{ adapter.quote("host_about") }} as listing_host_about,
        {{ adapter.quote("host_response_time") }} as listing_host_response_time,
        {{ adapter.quote("host_response_rate") }} as listing_host_response_rate,
        {{ adapter.quote("host_acceptance_rate") }} as listing_host_acceptance_rate,
        {{ adapter.quote("host_is_superhost") }} as listing_host_is_superhost,
        {{ adapter.quote("host_thumbnail_url") }} as listing_host_thumbnail_url,
        {{ adapter.quote("host_picture_url") }} as listing_host_picture_url,
        {{ adapter.quote("host_neighbourhood") }} as listing_host_neighbourhood,
        {{ adapter.quote("host_listings_count") }} as listing_host_listings_count,
        {{ adapter.quote("host_total_listings_count") }} as listing_host_total_listings_count,
        {{ adapter.quote("host_verifications") }} as listing_host_verifications,
        {{ adapter.quote("host_has_profile_pic") }} as listing_host_has_profile_pic,
        {{ adapter.quote("host_identity_verified") }} as listing_host_identity_verified,
        {{ adapter.quote("neighbourhood") }} as listing_neighbourhood,
        {{ adapter.quote("neighbourhood_cleansed") }} as listing_neighbourhood_cleansed,
        {{ adapter.quote("neighbourhood_group_cleansed") }} as listing_neighbourhood_group_cleansed,
        {{ adapter.quote("latitude") }} as listing_latitude,
        {{ adapter.quote("longitude") }} as listing_longitude,
        {{ adapter.quote("property_type") }} as listing_property_type,
        {{ adapter.quote("room_type") }} as listing_room_type,
        {{ adapter.quote("accommodates") }} as listing_accommodates,
        {{ adapter.quote("bathrooms") }} as listing_bathrooms,
        {{ adapter.quote("bathrooms_text") }} as listing_bathrooms_text,
        {{ adapter.quote("bedrooms") }} as listing_bedrooms,
        {{ adapter.quote("beds") }} as listing_beds,
        {{ adapter.quote("amenities") }} as listing_amenities,
        {{ adapter.quote("price") }} as listing_price,
        {{ adapter.quote("minimum_nights") }} as listing_minimum_nights,
        {{ adapter.quote("maximum_nights") }} as listing_maximum_nights,
        {{ adapter.quote("minimum_minimum_nights") }} as listing_minimum_minimum_nights,
        {{ adapter.quote("maximum_minimum_nights") }} as listing_maximum_minimum_nights,
        {{ adapter.quote("minimum_maximum_nights") }} as listing_minimum_maximum_nights,
        {{ adapter.quote("maximum_maximum_nights") }} as listing_maximum_maximum_nights,
        {{ adapter.quote("minimum_nights_avg_ntm") }} as listing_minimum_nights_avg_ntm,
        {{ adapter.quote("maximum_nights_avg_ntm") }} as listing_maximum_nights_avg_ntm,
        {{ adapter.quote("calendar_updated") }} as listing_calendar_updated,
        {{ adapter.quote("has_availability") }} as listing_has_availability,
        {{ adapter.quote("availability_30") }} as listing_availability_30,
        {{ adapter.quote("availability_60") }} as listing_availability_60,
        {{ adapter.quote("availability_90") }} as listing_availability_90,
        {{ adapter.quote("availability_365") }} as listing_availability_365,
        {{ adapter.quote("calendar_last_scraped") }} as listing_calendar_last_scraped,
        {{ adapter.quote("number_of_reviews") }} as listing_number_of_reviews,
        {{ adapter.quote("number_of_reviews_ltm") }} as listing_number_of_reviews_ltm,
        {{ adapter.quote("number_of_reviews_l30d") }} as listing_number_of_reviews_l30d,
        {{ adapter.quote("first_review") }} as listing_first_review,
        {{ adapter.quote("last_review") }} as listing_last_review,
        {{ adapter.quote("review_scores_rating") }} as listing_review_scores_rating,
        {{ adapter.quote("review_scores_accuracy") }} as listing_review_scores_accuracy,
        {{ adapter.quote("review_scores_cleanliness") }} as listing_review_scores_cleanliness,
        {{ adapter.quote("review_scores_checkin") }} as listing_review_scores_checkin,
        {{ adapter.quote("review_scores_communication") }} as listing_review_scores_communication,
        {{ adapter.quote("review_scores_location") }} as listing_review_scores_location,
        {{ adapter.quote("review_scores_value") }} as listing_review_scores_value,
        {{ adapter.quote("license") }} as listing_license,
        {{ adapter.quote("instant_bookable") }} as listing_instant_bookable,
        {{ adapter.quote("calculated_host_listings_count") }},
        {{ adapter.quote("calculated_host_listings_count_entire_homes") }},
        {{ adapter.quote("calculated_host_listings_count_private_rooms") }},
        {{ adapter.quote("calculated_host_listings_count_shared_rooms") }},
        {{ adapter.quote("reviews_per_month") }} as listing_reviews_per_month

    from source
)
select * from renamed
