version: 2

models:
  - name: gold_top_freq_reviewers
    description: >
      Este modelo indica quem foi o usuario com mais avaliações comentadas realizadas.
    
      
    columns:
      - name: count
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 10000
          - dbt_expectations.expect_column_values_to_not_be_null
      
      - name: reviewer_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null


  - name: gold_mean_score_neighb
    description: >
      Este modelo calcula a média dos scores por bairro.
    # pode ser nulo -- nenhum review ate o momento;



  - name: gold_count_most_reviewed
    description: >
      Este modelo retorna os anuncios com mais comentários, em ordem decrescente.

    columns:
      - name: listing_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: count
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null


  - name: gold_review_perfect_ratio
    description: >
      Retorna um ratio dos anuncions com comentários(reviews) calculado pelo número de reviews com a palavra perfect ou perfeito, pelo total de reviews, com um número mínimo de reviews >= 10.
    
    columns:
      - name: percentage
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      
#----  
  - name: gold_mean_price_property_type
    description: >
      Este modelo calcula o preço médio das listagens por tipo de propriedade.
    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: ['media_preco', 'listing_property_type']

    columns:
      - name: media_preco
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100_000
          - dbt_expectations.expect_column_values_to_not_be_null

  - name: gold_mean_price_neighbourhood
    description: >
      Este modelo calcula o preço médio das listagens por bairro.
    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: ['media_preco', 'listing_neighbourhood']

    columns:
      - name: media_preco
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100_000
          - dbt_expectations.expect_column_values_to_not_be_null

  - name: gold_mean_price_room_type
    description: >
      Este modelo calcula o preço médio das listagens por tipo de quarto.
    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list: ['media_preco', 'listing_room_type']
    columns:
      - name: media_preco
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100_000
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: listing_room_type
        tests:
          - dbt_expectations.expect_column_distinct_values_to_be_in_set:
              value_set:
                ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique

  - name: gold_mean_scores_host
    description: >
      Este modelo calcula a média das pontuações dos anfitriões.
    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            ['listing_host_id', 'listing_host_name', 'media_avaliacao']
    columns:
      - name: media_avaliacao
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 5
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: listing_host_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique

  - name: gold_count_property_host
    description: >
      Este modelo calcula a contagem de propriedades por anfitrião.
    tests:
      - dbt_expectations.expect_table_columns_to_match_set:
          column_list:
            ['listing_host_id', 'listing_host_name', 'contagem_imoveis']
    columns:
      - name: contagem_imoveis
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 200
          - dbt_expectations.expect_column_values_to_not_be_null
      - name: listing_host_id
        tests:
          - dbt_expectations.expect_column_values_to_not_be_null
          - dbt_expectations.expect_column_values_to_be_unique
